name: Build, Check Types, and Publish Packages

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - '.github/workflows/publish.yml'
  pull_request:
    paths:
      - 'packages/**'
      - '.github/workflows/publish.yml'

jobs:
  build-types-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@deepak-terse'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      
      - name: Configure npm for GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          echo "@deepak-terse:registry=https://npm.pkg.github.com/" >> ~/.npmrc
      
      - name: Verify pnpm installation
        run: |
          pnpm --version
          which pnpm
      
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
          echo "Store path: $STORE_PATH"
      
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build packages
        run: pnpm --filter @deepak-terse/hello-api... --filter @deepak-terse/hello-ui... build
      
      - name: Generate type definitions for all packages
        run: |
          pnpm --filter @deepak-terse/hello-api run types
          pnpm --filter @deepak-terse/hello-ui run types
      
      - name: Check for generated type definitions
        run: |
          test -f packages/hello-api/dist/index.d.ts
          test -f packages/hello-ui/dist/index.d.ts
      
      - name: Publish packages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: pnpm -r publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 